import type { NewsItem, ProductItem, VillageOfficial } from './types';

export const NEWS_DATA: NewsItem[] = [
  {
    id: 'news-1',
    category: 'Pemerintahan',
    title: 'Musyawarah Desa Tetapkan Prioritas Pembangunan Tahun Ini',
    date: '12 Juli 2026',
    summary: 'Pemerintah desa bersama warga menyepakati prioritas pembangunan infrastruktur, pelayanan publik, dan penguatan ekonomi lokal.',
    content: 'Musyawarah desa berlangsung di balai desa dengan partisipasi aktif tokoh masyarakat, perangkat desa, dan perwakilan dusun. Hasil pertemuan menetapkan beberapa program prioritas yang akan dikerjakan secara bertahap sepanjang tahun ini.\n\nFokus utama diarahkan pada perbaikan jalan lingkungan, penguatan layanan administrasi, serta dukungan bagi kegiatan ekonomi warga agar manfaat pembangunan dapat dirasakan lebih merata.',
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=80',
    author: 'Admin Desa',
    views: 184,
  },
  {
    id: 'news-2',
    category: 'Budaya',
    title: 'Pagelaran Seni Tradisi Meriahkan Peringatan Hari Desa',
    date: '8 Juli 2026',
    summary: 'Warga menampilkan kesenian tradisional sebagai bentuk pelestarian budaya dan penguatan identitas desa.',
    content: 'Kegiatan seni tradisi dihadiri oleh warga dari berbagai dusun dan menjadi ruang pertemuan yang hangat bagi masyarakat. Penampilan karawitan, tari, dan kesenian lokal lainnya menambah semarak peringatan hari desa.\n\nSelain hiburan, acara ini juga menjadi sarana edukasi bagi generasi muda agar tetap mengenal dan menjaga warisan budaya yang telah lama hidup di lingkungan desa.',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
    author: 'Tim Kesenian Desa',
    views: 201,
  },
  {
    id: 'news-3',
    category: 'Infrastruktur',
    title: 'Perbaikan Jalan Lingkungan Dimulai di Tiga Dusun',
    date: '3 Juli 2026',
    summary: 'Pekerjaan perbaikan jalan dilakukan untuk mendukung mobilitas warga dan memperlancar distribusi hasil pertanian.',
    content: 'Proyek perbaikan jalan lingkungan dilaksanakan secara bertahap pada tiga dusun yang memiliki tingkat lalu lintas tinggi. Pekerjaan ini diharapkan memperbaiki akses warga menuju sekolah, pasar, dan fasilitas kesehatan.\n\nPemerintah desa mengajak warga ikut mengawasi proses pekerjaan agar hasil pembangunan bisa bertahan lama dan sesuai kebutuhan lapangan.',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    author: 'Unit Pembangunan',
    views: 156,
  },
  {
    id: 'news-4',
    category: 'Sejarah',
    title: 'Ziarah dan Napak Tilas Jejak Awal Desa Digelar Bersama Pelajar',
    date: '28 Juni 2026',
    summary: 'Kegiatan edukatif ini mengajak pelajar mengenal asal-usul desa sekaligus belajar menghormati sejarah lokal.',
    content: 'Kegiatan napak tilas melibatkan pelajar, tokoh adat, dan perangkat desa untuk menelusuri jejak awal berdirinya desa. Peserta diajak mendengarkan cerita lisan dari para sesepuh dan mengunjungi beberapa titik bersejarah.\n\nAgenda ini diharapkan menumbuhkan rasa bangga dan tanggung jawab generasi muda terhadap sejarah serta identitas wilayah tempat mereka tumbuh.',
    image: 'https://images.unsplash.com/photo-1469571486292-bd7d1b3b7c8f?auto=format&fit=crop&w=1200&q=80',
    author: 'Seksi Kesejahteraan',
    views: 122,
  },
  {
    id: 'news-5',
    category: 'Pengumuman',
    title: 'Layanan Administrasi Tetap Buka pada Jam Kerja Normal',
    date: '20 Juni 2026',
    summary: 'Pemerintah desa mengingatkan warga untuk memanfaatkan layanan administrasi sesuai jadwal operasional kantor.',
    content: 'Seluruh layanan administrasi desa tetap dibuka pada hari kerja dengan jam operasional normal. Warga dapat mengurus surat keterangan, konsultasi data kependudukan, serta kebutuhan pelayanan lain sesuai prosedur yang berlaku.\n\nUntuk mempercepat proses, warga diimbau membawa dokumen pendukung yang diperlukan sejak awal pengajuan.',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
    author: 'Sekretariat Desa',
    views: 98,
  },
];

export const PRODUCTS_DATA: ProductItem[] = [
  {
    id: 'prod-1',
    name: 'Keripik Tempe Gurih',
    seller: 'Bu Siti',
    price: 15000,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1621939514649-280e2d2d13f6?auto=format&fit=crop&w=1200&q=80',
    phone: '6281234567801',
    category: 'Kuliner',
    description: 'Keripik tempe renyah dengan rasa gurih khas rumahan, cocok untuk camilan keluarga dan oleh-oleh.',
  },
  {
    id: 'prod-2',
    name: 'Anyaman Bambu Premium',
    seller: 'Kelompok Bambu Maju',
    price: 85000,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1596495578065-5b3d8c3d3c48?auto=format&fit=crop&w=1200&q=80',
    phone: '6281234567802',
    category: 'Kerajinan',
    description: 'Produk anyaman bambu untuk kebutuhan rumah tangga, dekorasi, dan suvenir dengan finishing rapi.',
  },
  {
    id: 'prod-3',
    name: 'Madu Hutan Asli',
    seller: 'Pak Darto',
    price: 120000,
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&w=1200&q=80',
    phone: '6281234567803',
    category: 'Madu & Herbal',
    description: 'Madu hutan asli dengan rasa alami, dikemas bersih dan aman untuk konsumsi harian.',
  },
  {
    id: 'prod-4',
    name: 'Beras Organik Desa',
    seller: 'Gapoktan Sejahtera',
    price: 68000,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1604335399105-a0c1a8b4f3b8?auto=format&fit=crop&w=1200&q=80',
    phone: '6281234567804',
    category: 'Pertanian',
    description: 'Beras organik hasil panen petani desa yang diproses secara higienis dan berkualitas baik.',
  },
  {
    id: 'prod-5',
    name: 'Kue Tradisional Kering',
    seller: 'Ibu Rini',
    price: 20000,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=1200&q=80',
    phone: '6281234567805',
    category: 'Kuliner',
    description: 'Aneka kue tradisional kering dengan rasa manis lembut, cocok untuk suguhan dan hantaran.',
  },
];

export const OFFICIALS: VillageOfficial[] = [
  {
    name: 'Slamet Raharjo',
    role: 'Kepala Desa',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Sri Wahyuni',
    role: 'Sekretaris Desa',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Mulyono',
    role: 'Kaur Keuangan',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Dewi Lestari',
    role: 'Kaur Umum',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Agus Santoso',
    role: 'Kasi Pelayanan',
    photo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Rina Puspita',
    role: 'Kasi Kesejahteraan',
    photo: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=800&q=80',
  },
];